;; -*- lexical-binding: t; -*-
(require 'init-straight)
(require 'init-tools)
(require 'init-editing)
(require 'init-web)
(require 'init-lisp)
(require 'init-swift)
(require 'init-python)
(require 'init-elixir)
(require 'init-note)
(require 'init-interface)
(require 'init-talonvoice)

(setq auto-mode-alist '(("/git-rebase-todo\\'"                         . git-rebase-mode)
                        ("\\.el\\'"                                    . emacs-lisp-mode)
                        ("\\.tsx\\'"                                   . tsx-ts-mode)
                        ("\\.ts\\'"                                    . typescript-ts-mode)
                        ("\\.jsx\\'"                                   . tsx-ts-mode)
                        ("\\.\\(c\\|m\\)?js\\'"                        . typescript-ts-mode)
                        ("\\.css\\'"                                   . css-mode)
                        ("\\.scss\\'"                                  . scss-mode)
                        ("\\.json\\'"                                  . json-ts-mode)
                        ("\\.ya?ml\\'"                                 . yaml-ts-mode)
                        ("\\.org\\'"                                   . org-mode)
                        ("\\.mdx?\\'"                                  . markdown-mode)
                        ("\\.\\(html\\|astro\\|vue\\|erb\\)\\'"        . web-mode)
                        ("\\.rest\\'"                                  . restclient-mode)
                        ("\\.\\(svg\\|jpe?g\\|png\\)\\'"               . image-mode)
                        ("\\.swift\\(interface\\)?\\'"                 . swift-mode)
                        ("\\.rs\\'"                                    . rust-ts-mode)
                        ("\\.py\\'"                                    . python-ts-mode)
                        ("\\(\\.rb\\|\\.ru\\|Gemfile\\|Rakefile\\)\\'" . ruby-ts-mode)
                        ("\\.exs?\\'"                                  . elixir-ts-mode)
                        ("\\.talon\\'"                                 . talonscript-mode)
                        ("Dockerfile"                                  . dockerfile-ts-mode)))


(provide 'init)
