;; -*- lexical-binding: t; -*-
(require 'init-straight)
(require 'init-tools)
(require 'init-editing)
(require 'init-web)
(require 'init-lisp)
(require 'init-swift)
(require 'init-python)
(require 'init-note)
(require 'init-interface)
(require 'init-talonvoice)

(setq auto-mode-alist '(("/git-rebase-todo\\'"            . git-rebase-mode)
                        ("\\.el\\'"                       . emacs-lisp-mode)
                        ("\\.tsx\\'"                      . tsx-ts-mode)
                        ("\\.ts\\'"                       . typescript-ts-mode)
                        ("\\.jsx\\'"                      . tsx-ts-mode)
                        ("\\.\\(c\\|m\\)?js\\'"           . typescript-ts-mode)
                        ("\\.css\\'"                      . css-mode)
                        ("\\.scss\\'"                     . scss-mode)
                        ("\\.json\\'"                     . json-ts-mode)
                        ("\\.yaml\\'"                     . yaml-ts-mode)
                        ("\\.org\\'"                      . org-mode)
                        ("\\.mdx?\\'"                     . markdown-mode)
                        ("\\.\\(html\\|astro\\)\\'"       . web-mode)
                        ("\\.\\(svg\\|jpe?g\\|png\\)\\'"  . image-mode)
                        ("\\.swift\\(interface\\)?\\'"    . swift-mode)
                        ("\\.rs\\'"                       . rust-ts-mode)
                        ("\\.py\\'"                       . python-ts-mode)
                        ("\\.rest\\'"                     . restclient-mode)
                        ("\\.talon\\'"                    . talonscript-mode)))


(provide 'init)
